### PR TITLE
Korean Translation

### PR DESCRIPTION
**Pull request by gjeodnd12165**
I couldn't Localize title of some advancements tactfully. :(
But it will not confuse to understand description.

### CODE REVIEW

**Comment by noobanidus** [comment]
*This is more of a general explanation of the terms for anyone who is translating.*

Thanks! Some of the advancement titles are confusing and are based on language references that are quite obscure. I think they would be quite difficult to translate directly.

I will explain the meanings of each one, and then give suggestions on how these could potentially be translated in a way that makes sense for players of other languages.

- Centennial simply refers to a 100 year anniversary or celebration of 100 years. This is the title for opening 100 containers (Chests, Trapped Chests, Barrels, Shulker Boxes and Minecarts-with-Chests)
- Penteconter refers to a type of ship from Ancient Greece. The name specifically means "fifty oars" or "fifty oared". The word can also be used to describe the commander or officer in charge of a troop of fifty men. This is the title for opening 50 containers.
- Close Quarters is a phrase that describes "a situation of being very or uncomfortably close to someone or something". A quarter is also the name used in American money to refer to a coin with a value of 25 cents. There is not much of a significant relationship between the two terms. This is the title for opening 25 containers.
- Disme a Dozen is a reference to the phrase "dime a dozen" which means "very common and of no particular value". This is a reference to the fact that loot containers are very common. A dime is a coin in American money with a value of 10 cents, which was originally called a "disme".
- "'X' Marks the Spot" is an [old phrase that refers to a cross or X shape marker on a map (more information on thefreedictionary)](https://idioms.thefreedictionary.com/X+marks+the+spot). This is a common "trope" in adventure stories, pirate stories, and the like, where a treasure map uses the cross or X shape to demonstrate where a treasure has been buried. It is also a reference to the movie Indiana Jones and the Last Crusade, where "X never, ever marks the spot" is said at the beginning of the movie, but the idea is subverted later in the story with a literal "X" symbol being on a floor. This is the title of the advancement for opening the first **chest** (specifically, rather than any container).
- Barrel Booty - "booty" refers to valuables, and is a common word in pirate and adventure stories to describe goods that have been stolen from another ship, or items that have been won. (Picked for the alliteration of both words starting with the letter B). This is the title of the advancement for opening the first **barrel** (specifically, rather than any container)
- Tunnel Treasures refers to the fact that Minecarts-with-Chests are found in tunnels and contain treasures. It was primarily picked for the alliteration of obth words starting with the letter T. This is the title of the advancement for opening the first **minecart** (specifically, rather than any container).
- Bounty Box - the box refers to the shulker box, and "bounty" is another word for a treasure or a reward. Again, this title was picked for the alliteration of both words starting with the letter B. This is the title of the advancement for opening the first **shulker box** (specifically, rather than any container).
- Socialised Loot - this advancement is rewarded whenever a player has opened one of every type of Loot container. It vaguely refers to the concept of "things being owned in common" from socialism, but is specifically referencing the fact that every container can be opened by every player, and every player receives loot.
- Belongs in a Museum - this advancement is the "root" advancement for Lootr and is granted (without alerting the player) whenever they first install Lootr. This is a reference to Indiana Jones and the Last Crusade specifically, where the character regularly says that items "belong in a museum".

Some of these are references to popular culture which may not translate well.

Others use specific synonyms for "treasure" that start with the same letter as the container they are describing (box, barrel, tunnel). Directly translating these probably isn't possible, so feel free to replace them with something else that you think would be suitable.

Finally, some of these use words that also reference numbers: disme (dime), quarter, penteconter and centennial. These could easily be replaced with "10 Containers", "25 Containers", or something similar. Alternately, if there are specific words or phrases in your language that are more suitable, feel free to use those instead.

**That said, ~~even some~~ most English-speaking players do not necessarily understand the meaning of these titles as I have based some of them on very, very obscure words and concepts.**

**Comment by noobanidus** [comment]
Thanks for the effort with this! I've posted a comment with some explanations of the current advancement names and some suggestions on what you could do to improve it for your language. If you'd like me to merge as-is without changes, let me know!

**Comment by noobanidus** [comment]
Additionally, there are parts of the `/lootr` command that haven't been translated or configured to be translatable. I would like to do this for a future release.

**Comment by gjeodnd12165** [comment]
Thanks for these explanations! Changed some advancement titles according to the description.
I appreciate to explain what I didn't know. I was asking the part of the number of opened loot containers. However,
there were things that I hadn't known about, such as the 'Belongs in a Museum' and the rhyme of the advancements.

It was not just the time to localize the mod but also improve my English skills.
Thanks to to you for commenting again, and it deserves to be merged.

**Pull request merged**
