### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Created ru_ru.json

### CODE REVIEW

**Comment by noobanidus** [comment]
Hi there!

Lootr has recently moved to CrowdIn for translations: https://crowdin.com/project/lootr

If you have an active CrowdIn account and you wish credit, please feel free to contribute there. Otherwise, I will include your suggestions if there is no response to this after a few weeks.

**Comment by mpustovoi** [comment]
I'll move it to Crowdin.

**Comment by mpustovoi** [comment]
Done.
Also corrected some errors, so this pull request is no longer relevant.

**Comment by noobanidus** [comment]
Thanks so much!

**Pull request closed without merging**
