### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by TheLegendofSaram**
Mexican and EU Spanish

### CODE REVIEW

**Comment by noobanidus** [comment]
Hey! We currently use Crowdin for translations: <https://crowdin.com/project/lootr>

EDIT: Whoops, sorry, I hit "comment and close" instead of just comment. 

If you use Crowdin, would you be willing to upload the translation there?

**Comment by TheLegendofSaram** [comment]
Yeah sure, no problem

**Comment by noobanidus** [comment]
Awesome, thank you so much! This means that it automatically gets applied to all of the different versions consistently.

**Comment by TheLegendofSaram** [comment]
I already updated all of the spanish translations in Crowdin it should be 100% translated across all of the versions now

**Comment by TheLegendofSaram** [comment]
Btw if it’s not too much to ask can you add a Mexican Spanish translation? it should be the same as the EU spanish cause I didn't use any mannerism in the translation and the names of the items should be the same in both versions.
Im asking because that way spanish users (whom tend to use more the mexican spanish variant) dont have to change the localization to the EU Spanish

**Comment by noobanidus** [comment]
@TheLegendofSaram Sorry for the delay! I thought I'd actually already done this until just now. I believe it should be set up now!

**Pull request closed without merging**
