### PR TITLE
Add LOLCAT translations

### PR DESCRIPTION
**Pull request by ScoutTheSaneless**
Yes, I actually did it!

### CODE REVIEW

**Comment by ScoutTheSaneless** [comment]
Did i do something wrong?

**Comment by noobanidus** [comment]
I've imported this manually via the Crowdin project, forgot to note that when I closed the request.

**Comment by ScoutTheSaneless** [comment]
~~i didnt notice the Crowdin, lolol~~ glad u took a peek at this!

**Comment by noobanidus** [comment]
I really need to advertise that somewhere; although it was only just today that I realized it supports LOLCAT anyway.

**Comment by ScoutTheSaneless** [comment]
XDDDDDDDDD

Ive known for a while and id've done it through there if i knew :3

**Comment by ScoutTheSaneless** [comment]
I believe it also handles some of the other joke languages too, like Shakespearean and Pirate

**Comment by noobanidus** [comment]
You're welcome to complete whatever's missing through Crowdin then. It's finally noticed and created the pull requests for the various branches, but I'll hold off on merging them as there are a few translations missing.

**Comment by ScoutTheSaneless** [comment]
Oop-
Lmk where to go and ill do my due diligence!

**Comment by noobanidus** [comment]
https://crowdin.com/project/lootr

**Pull request closed without merging**
